x-laravel-common: &laravel-common
  image: testsmith/practice-software-testing-${SPRINT}-api

  environment:
    PHP_OPCACHE_VALIDATE_TIMESTAMPS: 1
    DB_PORT: 3306
    DB_HOST: mariadb
    host: localhost

services:
  mariadb:
    image: yobasystems/alpine-mariadb:10.6.11
    container_name: toolshop-mariadb

    ports:
      - "3306:3306"

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: toolshop

    restart: unless-stopped

    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot" ]
      interval: 5s
      timeout: 3s
      retries: 20
      start_period: 10s

  db-init:
    <<: *laravel-common

    container_name: toolshop-db-init

    depends_on:
      mariadb:
        condition: service_healthy

    entrypoint:
      - php

    command:
      - artisan
      - migrate:fresh
      - --seed

    restart: "no"

  laravel-api:
    <<: *laravel-common

    container_name: toolshop-api

    depends_on:
      mariadb:
        condition: service_started

    restart: unless-stopped

  angular-ui:
    image: testsmith/practice-software-testing-${SPRINT}-ui
    container_name: toolshop-ui

    ports:
      - "4200:4200"

    environment:
      __VITE_ADDITIONAL_SERVER_ALLOWED_HOSTS: angular-ui

    volumes:
      - ./config/environment.ts:/app/src/environments/environment.ts

    command: >
      bash -c "ng serve --host 0.0.0.0 --port 4200"

    restart: unless-stopped

  web:
    image: testsmith/practice-software-testing-web
    container_name: toolshop-web

    ports:
      - "8091:80"

    depends_on:
      - laravel-api

    restart: unless-stopped

  selenium:
    image: selenium/standalone-chrome:4.44.0

    container_name: selenium

    ports:
      - "4444:4444"
      - "7900:7900"

    shm_size: "2gb"

    restart: unless-stopped