x-laravel-common: &laravel-common
  image: testsmith/practice-software-testing-${SPRINT}-api

  environment:
    PHP_OPCACHE_VALIDATE_TIMESTAMPS: 1
    DB_PORT: 3306
    DB_HOST: mariadb
    host: localhost

services:
  mariadb:
    image: yobasystems/alpine-mariadb:10.6.11
    container_name: toolshop-mariadb

    ports:
      - "3306:3306"

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: toolshop

    restart: unless-stopped

    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot" ]
      interval: 5s
      timeout: 3s
      retries: 20
      start_period: 10s

  db-init:
    <<: *laravel-common

    container_name: toolshop-db-init

    depends_on:
      mariadb:
        condition: service_healthy

    entrypoint:
      - php

    command:
      - artisan
      - migrate:fresh
      - --seed

    restart: "no"

  laravel-api:
    <<: *laravel-common

    container_name: toolshop-api

    depends_on:
      mariadb:
        condition: service_started

    restart: unless-stopped

  angular-ui:
    image: testsmith/practice-software-testing-${SPRINT}-ui
    container_name: toolshop-ui

    ports:
      - "4200:4200"

    environment:
      __VITE_ADDITIONAL_SERVER_ALLOWED_HOSTS: angular-ui

    volumes:
      - ./config/environment.ts:/app/src/environments/environment.ts

    command: >
      bash -c "ng serve --host 0.0.0.0 --port 4200"

    healthcheck:
      test: [ "CMD", "wget", "-q", "--spider", "http://127.0.0.1:4200" ]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 5s

    restart: unless-stopped

  web:
    image: testsmith/practice-software-testing-web
    container_name: toolshop-web

    ports:
      - "8091:80"

    depends_on:
      - laravel-api

    restart: unless-stopped

  selenium-chrome:
    image: selenium/standalone-chrome:4.44.0
    container_name: selenium-chrome

    ports:
      - "4444:4444"
      - "7900:7900"

    shm_size: "2gb"
    restart: unless-stopped

  selenium-firefox:
    image: selenium/standalone-firefox:4.44.0
    container_name: selenium-firefox

    ports:
      - "4445:4444"
      - "7901:7900"

    shm_size: "2gb"
    restart: unless-stopped

  selenium-edge:
    image: selenium/standalone-edge:4.44.0
    container_name: selenium-edge

    ports:
      - "4446:4444"
      - "7902:7900"

    shm_size: "2gb"
    restart: unless-stopped

  allure:
    image: frankescobar/allure-docker-service
    container_name: toolshop-allure

    profiles:
      - report

    environment:
      CHECK_RESULTS_EVERY_SECONDS: 1
      KEEP_HISTORY: 1

    ports:
      - "5050:5050"

    volumes:
      - ../allure-results:/app/allure-results
      - ../allure-report:/app/default-reports

    restart: unless-stopped