services:
  mariadb:
    image: yobasystems/alpine-mariadb:10.6.11
    container_name: toolshop-mariadb

    ports:
      - "3306:3306"

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: toolshop

    restart: unless-stopped

    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot" ]
      interval: 5s
      timeout: 3s
      retries: 20
      start_period: 10s

  laravel-api:
    image: testsmith/practice-software-testing-${SPRINT}-api
    container_name: toolshop-api

    environment:
      PHP_OPCACHE_VALIDATE_TIMESTAMPS: 1
      DB_PORT: 3306
      DB_HOST: mariadb
      host: localhost

    depends_on:
      - mariadb

    restart: unless-stopped

  angular-ui:
    image: testsmith/practice-software-testing-${SPRINT}-ui
    container_name: toolshop-ui

    ports:
      - "4200:4200"

    command: >
      bash -c "ng serve --host 0.0.0.0 --port 4200"

    restart: unless-stopped

  web:
    image: testsmith/practice-software-testing-web
    container_name: toolshop-web

    ports:
      - "8091:80"

    depends_on:
      - laravel-api

    restart: unless-stopped